version: '3'
services: 
    cts-mysql:
        build: 
            dockerfile: Dockerfile
            context: './cts-mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
    cts-user-ms:
        build:
            dockerfile: Dockerfile
            context: './cts-node-user-ms'
        ports:
            - '8001:8001'
    cts-node-api:
        build:
            dockerfile: Dockerfile
            context: './cts-node-api'
        ports:
            - '8000:8000'
    
    # redis:
    #     image: 'redis:latest'
    # nginx:
    #     restart: always
    #     build:
    #         dockerfile: Dockerfile.dev
    #         context: ./nginx
    #     ports: 
    #         - '3050:80'

